import Head from "next/head";
import Navbar from "../components/Navbar/Navbar";
import Content from "../components/Content/Content";
import Main from "../components/Main/Main";
import Footer from "../components/Footer/Footer";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Rario</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.container}>
        <Navbar />
        <Content />
      </div>

      <Main />
      <Footer />

    </div>
  );
}
